import React from 'react'
import { useState, useEffect } from 'react'
import Filter from './components/Filter'
import PersonForm from './components/PersonForm'
import Persons from './components/Persons'
import personService from './services/persons'

const App = () => {
  const [persons, setPersons] = useState([]) 
  const [newName, setNewName] = useState('')
  const [newNumber, setNewNumber] = useState('')
  const [filterName, setFilter] = useState('')

  const hook = () => {
    personService
      .getAll()
      .then(initialPersons => {
        setPersons(initialPersons)
      })
  }

  useEffect(hook, [])

  const addPersonWithoutDuplicates = (event) => {
    event.preventDefault()
    const personObject = {
      name: newName,
      number : newNumber,
      // id: persons.length + 1, // id is generated by json-server
    }

    const foundPerson = persons.find(p => p.name === newName)
    if (foundPerson) {
      console.log('%cApp.js line:34 foundPerson', 'color: #007acc;', foundPerson);
      if (window.confirm(`${newName} is already added to phonebook, replace the old number with a new one?`)) {
        
        const changedPerson = { ...foundPerson, number: newNumber }
        personService
          .update(foundPerson.id, changedPerson)
          .then(returnedPerson => {
            setPersons(persons.map(p => p.id !== foundPerson.id ? p : returnedPerson))
            setNewName('')
            setNewNumber('')
          })
          .catch(error => {
            alert(
              `the person '${foundPerson.name}' does not exist on server`
            )
            setPersons(persons.filter(p => p.id !== foundPerson.id))
          })
      }
    }
    
    else {
      personService
        .create(personObject)
        .then(returnedPerson => {
          setPersons(persons.concat(returnedPerson))
          setNewName('')
          setNewNumber('')
        })
    }
    console.log('button clicked', event.target)
  }
  
  const handleNameChange = (event) => {
    console.log(event.target.value)
    setNewName(event.target.value)
  }

  const handleNumberChange = (event) => {
    console.log(event.target.value)
    setNewNumber(event.target.value)
  }

  const handleFilterChange = (event) => {
    console.log(event.target.value)
    setFilter(event.target.value)
  }

  const personsToShow = 
  persons.filter(person => person.name.toLowerCase().includes(filterName.toLowerCase()))

  const deleteRecord = (id) => {
    const person = persons.find(p => p.id === id)
    if (window.confirm(`Delete ${person.name}?`)) {
      personService
        .deleteRecord(id)
        .then(() => {
          setPersons(persons.filter(p => p.id !== id))
        })
        .catch(error => {
          alert(`the person '${person.name}' was already deleted from server`)
          setPersons(persons.filter(p => p.id !== id))
        })
    }
  }

  return (
    <div>
      <h2>Phonebook</h2>
      <Filter filterName={filterName} handleFilterChange={handleFilterChange} />
      <h3>Add a new</h3>
      <PersonForm addPersonWithoutDuplicates={addPersonWithoutDuplicates}
        newName={newName} handleNameChange={handleNameChange}
        newNumber={newNumber} handleNumberChange={handleNumberChange}
      />
      <h3>Numbers</h3>
      <Persons personsToShow={personsToShow} deleteRecord={deleteRecord} />
    </div>
  )
}

export default App