POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Ensure that everything still works",
  "author": "Test Author",
  "url": "http://localhost:3003/api/blogs",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NDllNzUzMGM4OTc5MTM3NTUxMzgyZWYiLCJpYXQiOjE2ODgxMDcwNjN9.9U0OOoXN4UaW11EzlG45cWPu6hmWuII3ym5vRV98-D4

{
  "title": "Ensure that everything still works 3",
  "author": "Test Author",
  "url": "http://example.com",
  "likes": 1337
}