POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Ensure that everything still works",
  "author": "Test Author",
  "url": "http://localhost:3003/api/blogs",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Ensure that everything still works 2",
  "author": "Test Author",
  "url": "http://example.com",
  "likes": 13
}