POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Victor James",
  "number": "45-940-65949"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Base James"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "45-940-65949"
}
